import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image';
import styles from '../styles/Home.module.css'
import { sanityClient, urlFor } from '../lib/sanity';

const recipesQuery = `*[_type == "recipe"]{
  _id,
  name,
  slug,
  mainImage,
}`;

export default function Home({ recipes }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kap&apos;s Kitchen 🍍</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Kap&apos;s Kitchen 🍍</h1>
      <ul className="recipes-list">
        {recipes.map((recipe) => {
          return (
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <img src={urlFor(recipe.mainImage).url()} alt={recipe.name} />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          )
        })}
      </ul>

    </div>
  )
}

export const getStaticProps = async () => {
  const recipes = await sanityClient.fetch(recipesQuery);
  console.log(recipes);
  return { props: { recipes } };
};
